### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by flypie** [floooh/chips#14]
I was wondering if there is any documentation on creating a new emulation? or perhaps how to change the code that is in the emulators ROM? I'm trying to modify the LC80 emulation so I can play with the interrupt handling on the CTC.
I'd also like to be able to add some 74 series chips to test out my glue. 

I suppose the ultimate would be to be able to load up a KiCad Schematic and emulate that.

**Comment by floooh** [comment]
Hi, there's a short embedding guide in the systems subdirectory: https://github.com/floooh/chips/tree/master/systems#embedding-guide

It's a bit outdated here and there, but all in all it should still be valid.

In general I want to put most of the detailed documentation into the headers themselves, most chip headers have this missing, but the CPU header docs are in pretty good shape, for instance here's how the Z80's interrupt handling works (a bit non-trivial because of the Z80's daisy chain protocol):

https://github.com/floooh/chips/blob/master/chips/z80.h#L228

Usually this protocol is implemented in the Z80 family chips, for the CTC this function is called:

https://github.com/floooh/chips/blob/6cf1ac795eee747f8e6774e77c86991ef7277eec/chips/z80ctc.h#L316

...when the CPU is in an interrupt acknowledge machine cycle: 

https://github.com/floooh/chips/blob/6cf1ac795eee747f8e6774e77c86991ef7277eec/systems/lc80.h#L527-L534

The LC80 operating system itself doesn't issue interrupts as far as I saw (only when programmed through user code), but you can step-debug through the Z9001 emulation (which uses CTC interrupts for its system clock), for instance you can set breakpoints in various functions of the CTC's interrupt protocol response routine here:

https://github.com/floooh/chips/blob/6cf1ac795eee747f8e6774e77c86991ef7277eec/chips/z80ctc.h#L316

Hope this helps! If you're stuck somewhere, just add more questions to this thread :)

**Comment by flypie** [comment]
Thanks that is great.
I ended up deleting doing a small mod allowing the ROM size to be smaller than the ROMs, deleting the lc80-roms.h file and replacing the lc80_2k.bin file and this causes the .h file to be built, in the next make. There doesn't seem to be a date check.
One thing I did notice was that if I just put a RETIin the interrupt handler, then the first interrupt would be handled but no others, I assume because they have been disabled. From what I can remember of real Z80s DI to be called to disable them.

[IM2.zip](https://github.com/floooh/chips/files/3750491/IM2.zip)

**Comment by floooh** [comment]
> ...and this causes the .h file to be built, in the next make. There doesn't seem to be a date check.

The ```lc80-roms.h``` file should be rebuild when either the ```lc80-roms.yml``` file changes, or the ROM dump file pointed to by that YAML file (https://github.com/floooh/chips-test/blob/master/examples/roms/lc80-roms.yml).

The code-generation runs via this python script: https://github.com/floooh/chips-test/blob/master/fips-files/generators/dump.py, there *should* be a timestamp check happening there's unless it's a bug, but I haven't noticed any strange behaviour (I'm using the same check for all code generation stuff, also in other fips projects).

Regarding behaviour of the RETI instruction: interrupts are disabled "automatically" during the interrupt acknowledge protocol and before the interrupt service routine is entered. A RETI will not automatically enable interrupts though, that's up to the interrupt service routine. Usually this happens at the start (if the ISR can itself be interrupt), or at latest right before the RETI instruction.

Here's a snippet from the RETI description in the Z80 manual:

<img width="465" alt="Screen Shot 2019-10-22 at 10 52 50 AM" src="https://user-images.githubusercontent.com/1699414/67271100-301fde00-f4ba-11e9-94c9-d6d23b603207.png">

However, both RETI and RETN *will* move the status of the IFF2 flag into IFF1 (this is only documented for the RETN instruction, but according to the "Undocumented Z80 Documented" PDF both RETI and RETN behave the same (see page 20 "Things affecting the interrupt flip-flops" here: https://github.com/floooh/emu-info/blob/master/z80/z80-documented.pdf

Cheers :)

**Comment by flypie** [comment]
I just checked and under the Visual Studio touch the bin files does not cause the h files to be built. I also did a build on Linux here is the long from the shell.

[Untitled-1.txt](https://github.com/floooh/chips/files/3755449/Untitled-1.txt)
