### ISSUE TITLE
Question about using CLion with the generated files for chipstest

### ISSUE THREAD

**Issue by ghost** [floooh/chips#42]
Hello, 
I build everything successfully on the command line. Few questions:

1. Why are the executables are created under the fips-deploy\chips-test\win64-vstudio-release\ directory? 
2. CLion does not identify any of the CMake targets and hence non of the source files, how do you work with the chips-test projects inside an IDE, I spent so much time trying to make Clion work with this, but I must be doing something wrong. 
![image](https://user-images.githubusercontent.com/18743986/92603059-89058a00-f2b7-11ea-970a-db1caa80d8e9.png)

Thanks,

**Comment by QuantScientist** [comment]
I think I am going to let oryol go and try this as long as this works in CLion. 
Thanks

**Comment by floooh** [comment]
The executables are in the fips-deploy directory so that they can be easier found. Otherwise they would be buried deep in the cmake build directory somewhere. I don't have experience with CLion, sorry. Fips projects should work with Visual Studio, VSCode and Xcode. I merged a PR for CLion at some point, but I'm not using this on a daily basis.

**Comment by QuantScientist** [comment]
So this is not a classic Cmake project that can be edited with Clion? I still need fips style stuff? 
Thanks
