### ISSUE TITLE
[c64.h] glitch implementing a mapped I/O device

### ISSUE THREAD

**Issue by nippur72** [floooh/chips#47]
I'm trying to implement my own memory mapped I/O device on the C64. Something very simple: when I read the location 16384 a value is returned and the value itself is incremented for the next read.

I modified `_c64_tick()` this way:
```c
// ...
else if (mem_access) {
        if (pins & M6502_RW) {            
            unsigned char data;
            if(addr == 16384) {
                /* read from my device */
                data = kk++;
                if(kk==(64+40)) kk=64;
            }
            else data = mem_rd(&sys->mem_cpu, addr); // normal read
            M6502_SET_DATA(pins, data);
        }
// ...
```

The issue I'm experiencing is that sometimes bytes (in groups of 3) are completely lost, they are not received by the CPU as shown in the picture below:

![issue](https://user-images.githubusercontent.com/2598443/101377261-e2c72180-38b1-11eb-900c-5b8e35e3e660.png)

This is the assembly program I use to read the bytes:

```asm
pippo:
    lda 16384
    jsr $FFD2
    jmp pippo
```
Is there something else I should consider in `_c64_tick()` or is this unexpected behavior? 

Thank you for your help.

**Comment by floooh** [comment]
Only reason I could think of is the C64's badlines, during a badline the CPU is frozen for an entire scanline and no memory accesses are performed, this happens every 8th scanline. If your memory-mapped device doesn't have a handshake mechanism the CPU might miss updates while it is frozen during a badline.

That's why fast loaders often disable video output (so that only the background color is shown), because this also disabled badlines and the CPU is available for the entire frame.

If you quickly want to check if the badlines are the problem, remove this if() check: 

https://github.com/floooh/chips/blob/3cb521f5ba8322b63c023188cfe6f76d725abac5/systems/c64.h#L695

This will let the CPU run at full speed and not freeze during badlines.

**Comment by floooh** [comment]
...on the other hand, the simple ```kk++``` code you've shown above shouldn't cause any drops during badlines, because kk would be incremented unless the code actually arrives in the memory read access.

In that case maybe it's a side effect of the 6502 doing a memory access in each tick, even if no memory access would actually be needed (this is different from the Z80 which has explicit memory access cycles). Could be a side effect of an interrupt happening. Hard to remote-analyze.

**Comment by floooh** [comment]
...this blog post contains some info on 6502 memory access:

https://xania.org/201405/jsbeeb-getting-the-timings-right-cpu

Search for "we can see what memory accesses happen on each clock tick".

**Comment by nippur72** [comment]
ok thanks, I think I have figured it out! Apparently it looks like there are times when the CPU reads 4 times within the same instruction cycle (the first three the data is lost). So my virtual device must increment the byte (`kk++`) only when a complete instruction is finished. This can be easily done by listening to the changes of the `SYNC` pin. I guess this is one of the purposes of this pin (the other being able to intercept the `RTI` instruction perhaps?)

It's cool that your emulator also emulates side effects ! 😄  

BTW I'm using your C64 to make it connect to a internet-BBS, see [http://bbs.retrocampus.com](http://bbs.retrocampus.com). I'm going to talk about it in "Retro Magazine", I'll send you the link when the english version gets issued.

I also have some minor fixes for the C64 keyboard that I'll send separately as a pull request.
