### ISSUE TITLE
surprising behaviour of cycle-stepped z80 after PC reset

### ISSUE THREAD

**Issue by rofl0r** [floooh/chips#63]
maybe related : #61

after the prefetch function is called, or init/reset, the first call to cycle() results in PC increased by 1, and op_done() flagged, to actually get the first instruction executed you have to call cycle() again in a loop until op_done() and if adding up the cycles you'll end up with one too many.

here's a naive implementation that uses your z80 to emulate the behaviour of other z80 core's z80_step() function:

```c
static unsigned csz80_step_one(csz80_state* csz) {
  unsigned cyc = 0;
  do {
    csz->pins = csz80_tick(&csz->cpu, csz->pins);
    if (csz->pins & Z80_MREQ) {
      const uint16_t addr = Z80_GET_ADDR(csz->pins);
      if (csz->pins & Z80_RD) {
        uint8_t data = Z80_READ_BYTE(z->userdata, addr);
        Z80_SET_DATA(csz->pins, data);
      } else if (csz->pins & Z80_WR) {
        uint8_t data = Z80_GET_DATA(csz->pins);
        // do not write again, it's already done by our z80
        // memory[addr] = data;
      }
    } else if(csz->pins & Z80_IORQ) {
      const uint16_t port = Z80_GET_ADDR(csz->pins);
      if (csz->pins & Z80_RD) {
        //in(z, port);
      } else if (csz->pins & Z80_WR) {
        //out(z, port, 0);
      }
    }
    ++cyc;
  } while(!csz80_opdone(&csz->cpu));
  return cyc;
}
```
in order to get e.g. the first instruction `xor a` executed, you have to call that step function twice and the total cycles will be 5 instead of 4, while the PC afterwards is 2 instead of 1.

**Comment by floooh** [comment]
z80_opdone() triggers on M1/T2, not M1/T1. This is because instruction execution overlaps with the next instruction fetch (so the result of the last instruction may only be ready in M1/T2), and debuggers (for which the z80_opdone() function is mainly intended) need to be able to read the result of the last instruction.

To get to a "clean start" for 'instruction cycle counting' you need to run the emulation until the first ```z80_opdone() == true``` after z80_prefetch(), this shouldn't be needed in an actual system emulator though (it's only useful for debuggers and instruction-timing tests).

For example see here: the ```step()``` function runs one instruction and returns the number of cycles, and the ```prefetch()``` function runs ```step()``` once:

https://github.com/floooh/chips-test/blob/2f45c557cb1f4420f063f7b89288619a3411e8bc/tests/z80-test.c#L73-L85

After calling this prefetch() function, every call to step() will execute the next instruction and return with the correct cycle count for this instruction.

**Comment by rofl0r** [comment]
thanks for the explanation. yes, this is basically what i ended up doing myself.
