### ISSUE TITLE
Increase address range of mem mapper

### ISSUE THREAD

**Issue by nullobject** [floooh/chips#9]
I am building an arcade emulator, and using `mem.h` to create my main memory map. This works very nicely ❤️ 

However, when I tried to use `mem.h` to map some of the graphics ROMs, I realised that it is limited to addressing only 64KB. The Rygar tile ROMs are actually 128KB.

Is there any chance we could bump this up higher (maybe 1MB)? I tried editing `mem.h` locally by increasing the `MEM_ADDR_RANGE` and changing the `addr` arguments to all be `uint32_t`, which seemed to work fine.

Was there any reason you set the hard limit at 64KB? I realise that more pages will be created in the mem mapper if we bump the limit, but is there a performance penalty?

**Comment by floooh** [comment]
Hi, no specific reason, I just didn't expect that any 8-bit systems would have more then 16 address lines :)

However if the tile ROMs are "hardwired" to the video hardware and the CPU doesn't have access to the tile data, it might be better to not use a mem.h memory mapper inbetween (it would be just additional overhead).

For instance in the Bomb Jack emulator I keep the tile data in simple C arrays:

https://github.com/floooh/chips-test/blob/88eb9eaae5efc7af84b9fd74685a5b47ceb648ea/examples/sokol/bombjack.c#L148-L167

In the Bomb Jack machine, each of the tile ROMs basically has its own address- and data-bus to the video-layer- and sprite-hardware, if everything would go over one bus shared with the CPU, there wouldn't nearly enough bandwidth to create the video image (I only realized this after I wrote my blog post).

I'll keep the bug open for when I get around working on emulator stuff again :) But since you have a workaround I guess it isn't too critical :)

**Comment by nullobject** [comment]
> However if the tile ROMs are "hardwired" to the video hardware and the CPU doesn't have access to the tile data, it might be better to not use a mem.h memory mapper inbetween (it would be just additional overhead).

Good point. That's what I was doing originally, I just wanted to use `mem.h` to concatenate the ROMs for me automatically. But I guess this comes at a performance cost.

> In the Bomb Jack machine, each of the tile ROMs basically has its own address- and data-bus to the video-layer- and sprite-hardware, if everything would go over one bus shared with the CPU, there wouldn't nearly enough bandwidth to create the video image (I only realized this after I wrote my blog post).

Rygar is very similar. There are four sets of ROMs for graphics: text, fg, bg, and sprites. The CPU doesn't have access to any of these ROMs, they are directly wired to each graphics layer. The Rygar graphics layers can each access up to 64KB of tile data.

Feel free to close this "issue", I fully get that there isn't much point in increasing the address space beyond 16-bits since it lives in a library with CPUs that can't access more than that.
